### ISSUE TITLE
Parameters popup covers up the view

### ISSUE THREAD

**Issue by zheins** [CIDARLAB/3DuF#116]
<img width="406" alt="screen shot 2018-04-17 at 5 00 29 pm" src="https://user-images.githubusercontent.com/10240498/38896494-dd7c88a4-4260-11e8-893d-a3b220d6c1b4.png">

@JLippai

**Comment by rkrishnasanka** [comment]
Added transparency to the parameters window when enabled using right-click. 

Commit : 9c7156b7ce95164bc540fca4440935f15b8e6a31
