### ISSUE TITLE
Valve3D does not delete properly

### ISSUE THREAD

**Issue by zheins** [CIDARLAB/3DuF#118]
<img width="139" alt="screen shot 2018-04-17 at 5 08 02 pm" src="https://user-images.githubusercontent.com/10240498/38896875-ec3dcffa-4261-11e8-91f2-4e328d4b79ab.png">

This also applies to other primitives that have control layer components (rotary mixer)

<img width="264" alt="screen shot 2018-04-17 at 5 33 34 pm" src="https://user-images.githubusercontent.com/10240498/38899318-792264c8-4265-11e8-97c9-ed81cbd8ba84.png">

@JLippai

**Comment by rkrishnasanka** [comment]
@JLippai this is happening because by default, its only selecting the active layer components. We need to enable multilayer selection for single right click selection.

**Comment by rkrishnasanka** [comment]
I have fixed the selection system to include the multiple features on the canvas via 'component' abstraction. I haven't however tested #121 with regards to this. I will look at it next after @JLippai has finished the selection tool. I already made changes to it and I don't want to make all the changes right now. However the deletion works fine now !!!
