### ISSUE TITLE
Hard to select small components when zoomed in

### ISSUE THREAD

**Issue by zheins** [CIDARLAB/3DuF#120]
<img width="671" alt="screen shot 2018-04-17 at 5 22 17 pm" src="https://user-images.githubusercontent.com/10240498/38898745-e88309be-4263-11e8-8d5c-36225389b0be.png">

I'm trying to right click and delete the small circle at the top, but it keeps selecting the long channel.

@JLippai

**Comment by rkrishnasanka** [comment]
Should be addressed by the selection tool in commit b3eced69b67822855a9530696fc2e4a62ef99c80
