### ISSUE TITLE
Component parameter changes don't apply to control layer

### ISSUE THREAD

**Issue by zheins** [CIDARLAB/3DuF#121]
<img width="155" alt="screen shot 2018-04-17 at 5 37 49 pm" src="https://user-images.githubusercontent.com/10240498/38899524-1bf7d7d2-4266-11e8-97d9-0b1eea9b8f69.png">

**Comment by rkrishnasanka** [comment]
@JLippai this error has the same as #118 . We need to change the way the selection works.
