### ISSUE TITLE
It's possible to lose the working canvas space if you zoom out

### ISSUE THREAD

**Issue by zheins** [CIDARLAB/3DuF#122]
There should maybe be a re-center/re-zoom or some defaults to snap back to

<img width="1425" alt="screen shot 2018-04-17 at 5 46 34 pm" src="https://user-images.githubusercontent.com/10240498/38899894-669eb296-4267-11e8-865c-9e1d527ebf8e.png">

**Comment by rkrishnasanka** [comment]
The view can now be reset using the `F` key. This will work post commit https://github.com/CIDARLAB/3DuF/commit/0d6a66f19c3ecc7247641136e9bc0e86f1960d32 .
