### ISSUE TITLE
Control Layer not inverted

### ISSUE THREAD

**Issue by MohUddin** [CIDARLAB/3DuF#123]
When designing a transposer on 3DuF the control layer is misaligned when milled out. This issue can be resolved by inverting the control layer.

NOTE: On the .SVG files the designs seem to line up properly, but when physically milled and assembled one of the chips needs to be flipped.

![singletransposer_flow](https://user-images.githubusercontent.com/32975339/40728366-f1a5f834-63f7-11e8-8216-13ff29e2b59f.JPG)

![singletransposer_control](https://user-images.githubusercontent.com/32975339/40728357-ee3df304-63f7-11e8-8526-803412aa31ee.JPG)

**Comment by rkrishnasanka** [comment]
This issue is open on #67 . Please check and see if the issues already exist before posting it. Its easier for us to keep track of the problems in 3DuF.
