### ISSUE TITLE
Add option to create horizontal droplet generator

### ISSUE THREAD

**Issue by maniwu** [CIDARLAB/3DuF#126]
Currently, 3DuF only has the option to create a vertical droplet generator. A horizontal option, similar to the transposer, would be great.

**Comment by rkrishnasanka** [comment]
Fixed as of Commit - 0609771abbf278c3f9817ea312f407683b04b11d

**Comment by rkrishnasanka** [comment]
Also @maniwu feedback on rotation vs horizontal/vertical would be appreciated.
