### ISSUE TITLE
Flipping flow or control layer for svg files

### ISSUE THREAD

**Issue by maniwu** [CIDARLAB/3DuF#127]
When creating chip designs, either the flow or control layer should be flipped since, during assembly, either of the layers will be flipped in order to have the milled faces align. 

For example, a milled chip below has valves (in the center of the design) that do not align on the flow and control layers despite appearing aligned on the json and svg files.

![img_0714](https://user-images.githubusercontent.com/39596986/41741279-9d12248c-7568-11e8-8ae0-1cc1673bc7f3.JPG)

<img width="1089" alt="screen shot 2018-06-21 at 3 36 04 pm" src="https://user-images.githubusercontent.com/39596986/41741355-d541ae2c-7568-11e8-8fe6-341e0ff06065.png">

**Comment by rkrishnasanka** [comment]
@maniwu did you not flip the control layer before fabricating? I thought the rest of the group does this, Ideally 3DuF needs to do this but I assumed that it was part of standard procedure.

**Comment by rkrishnasanka** [comment]
Also, the issue is already in the system - refer to issue #67 . Please try to extend existing issues.
