### ISSUE TITLE
Curved Mixers disappear when moved to desired location 

### ISSUE THREAD

**Issue by peytontierney** [CIDARLAB/3DuF#137]
When attempting to moved a curved mixer to a desired location, the central connections of the mixer disappear. If moved slightly up, down, left, or right the entirety of the mixer reappears. This incomplete mixer is also saved in the svg file. 

<img width="364" alt="screen shot 2018-07-24 at 4 45 22 pm" src="https://user-images.githubusercontent.com/39597010/43165467-fda1aa3a-8f61-11e8-8694-52039a77c6d5.png">

<img width="1094" alt="screen shot 2018-07-25 at 12 12 37 pm" src="https://user-images.githubusercontent.com/39597010/43213237-2390a8c0-9004-11e8-9f91-64f01a7cb7d3.png">

**Comment by rkrishnasanka** [comment]
Can you tell me by how much you move the mixer?

**Comment by peytontierney** [comment]
1 arrow’s worth using the move function.
