### ISSUE TITLE
File export to svg

### ISSUE THREAD

**Issue by brevid** [CIDARLAB/3DuF#158]
When exporting the files to SVG each shape is not formed properly, it seems to not be connecting first and last point of a shape together and instead connects to the origin.
<img width="356" alt="Annotation 2019-12-18 225613" src="https://user-images.githubusercontent.com/45141365/71084649-de5db080-21e9-11ea-8075-4003c0493f7c.png">

**Comment by rkrishnasanka** [comment]
@brevid its very likely that you tool is only rendering it like this, if you can upload a zip of the SVG we can triage it. I'll label it as wontfix for now

**Comment by rkrishnasanka** [comment]
Closing this because we need more info
