### ISSUE TITLE
connection's parameter manipulation

### ISSUE THREAD

**Issue by h12390** [CIDARLAB/3DuF#162]
updateParameter(key, value) in connection.js does not work as expected. Need to fix it soon. We also need to double-check the rest of the parameter-related code.

**Comment by rkrishnasanka** [comment]
Ok looks like we found the differences in what the `getParams()` returns the `__params.parameters` and `__params.parameters`

In `features.js`:

```
    getParams(){
        return this.__params.parameters;
    }
```

In `connection.js`:

```
    getParams(){
        return this.__params;
    }
```

In `component.js`:

```
    getParams(){
        return this.__params;
    }
```

In `textfeature.js`:
```
    getParams(){
        return this.__params.parameters;
    }
```

**Comment by rkrishnasanka** [comment]
I will change the function name here

**Comment by rkrishnasanka** [comment]
@murrayLF this was one of the problems with how the params API is being used

**Comment by rkrishnasanka** [comment]
This has been rectified with the typescript port, the return type hints should make things more clear
