### ISSUE TITLE
The valves cannot be drawn correctly, the two sides of it will be connected sometimes

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#183]

**Comment by zyrrron** [comment]
[](url)


[jsonfiles.zip](https://github.com/CIDARLAB/3DuF/files/4900383/jsonfiles.zip)
![image](https://user-images.githubusercontent.com/38414177/87107726-1d8d4500-c293-11ea-8f38-d71b24ee0f82.png)

**Comment by rkrishnasanka** [comment]
I implemented a fix in commit 6a0b97543bb4abae0aa9ba475f20d2227f8422a5 . Will close this if problems persist.

**Comment by rkrishnasanka** [comment]
@zyrrron any issues so far or can I close this issue ?
