### ISSUE TITLE
3DuF not import the right width and length of the device on import

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#187]
The json file we created and saved on 3DuF cannot be shown correctly when we drag it to 3DuF again. The scale will shows as the default value but not the values we set for the device.

[3duf_scale.zip](https://github.com/CIDARLAB/3DuF/files/4979723/3duf_scale.zip)

**Comment by rkrishnasanka** [comment]
Fixed as of e738f71
