### ISSUE TITLE
Laser Cutting problem

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#188]
@zamsam 
When you click on Laser Cutting (.SVG) option (in the bottom menu), nothing happens. 
There are no files being created. 
It only works for CNC (.SGV)

**Comment by rkrishnasanka** [comment]
Can you attach a design file for which this action is not working? My guess is that its a single component that has some bug that prevents it from working.

**Comment by rkrishnasanka** [comment]
The issue was a missing implementation for the `INVERSE` render for the `PUMP3D`. Need to add a method in a future commit to catch these missing errors.

Fixed as of 14878db
