### ISSUE TITLE
Add the possibility of inverting flow layer ports

### ISSUE THREAD

**Issue by zamsam** [CIDARLAB/3DuF#190]
I need to have the possibility of inverting flow layer ports so I can fabricate them along with control ports during the laser cutting. VIAs should not be inverted in this case.

![Screen Shot 2020-08-03 at 9 34 00 AM](https://user-images.githubusercontent.com/35291778/89188309-7a1b1180-d56c-11ea-91cb-0250a595f98d.png)

**Comment by rkrishnasanka** [comment]
@zamsam so can I close this issue ?

**Comment by zamsam** [comment]
Sure! Thanks!

--
Samuel MD Oliveira
Postdoctoral Research Associate, DAMP Core Facility Manager
Electrical and Computer Engineering Department
DAMP Lab @ Biological Design Center
Boston University
+1 857 310 9593<tel:+1%20857%20310%209593>
https://www.damplab.org/

On 5. Aug 2020, at 15.07, Radhakrishna Sanka <notifications@github.com> wrote:

﻿

@zamsam<https://github.com/zamsam> so can I close this issue ?
