### ISSUE TITLE
Sometimes there are no rotation part for a valve in the json file given by 3duf.

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#193]
**Describe the bug**

**To Reproduce**

Or add a GIF

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
[
[Device-3-constant-feeding-1.txt](https://github.com/CIDARLAB/3DuF/files/5469231/Device-3-constant-feeding-1.txt)

](url)

**Comment by rkrishnasanka** [comment]
Hey @zyrrron can you describe this issue better ?

**Comment by zyrrron** [comment]
It has been a long time and I cannot open this text now. So I also don't know what I really want for this bug. Just forget about it, if I find any other problem I will open a new issue in github.
