### ISSUE TITLE
Fixing issues with the component designs and their port locations

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#220]
@ryu-bu it looks good, I some slight modifications:

1. Turns out that I forgot to have some channels to the transposer - green (it'll have control ports - pink)
<img width="281" alt="Screen Shot 2021-02-06 at 1 09 28 PM" src="https://user-images.githubusercontent.com/855696/107126275-e446a300-687c-11eb-8016-5a8ef2ce1467.png">

2. Fixes to the mux3d component (change the circles to be the component ports - green) (Add red circles for valve in control layer - pink)
<img width="570" alt="Screen Shot 2021-02-06 at 1 23 06 PM" src="https://user-images.githubusercontent.com/855696/107126632-0a6d4280-687f-11eb-95eb-593fbd876c95.png">

**Comment by ryu-bu** [comment]
made a PR #221  for this issue.

**Comment by rkrishnasanka** [comment]
Looks like everything is cleared now 🥇
