### ISSUE TITLE
Unable to add features onto 2nd level 

### ISSUE THREAD

**Issue by msuazox** [CIDARLAB/3DuF#243]
**Describe the bug**
When trying to add components to a level 2, no components show up/ are able to be put onto the device 

**To Reproduce**
1. Go to 3duf
2. Click on + to select layer and add a second 
3. Select flow layer 
4. Try to add component (any) 
5. Nothing adds to layer (see video) 

Or add a GIF

**Expected behavior**
I expect to be able to add components to a second layer 

**Screenshots**

**Desktop (please complete the following information):**
 - OS
 - Chrome  
 - Big Sur 11.2.3 

**Additional context**

https://user-images.githubusercontent.com/61927568/115805642-5e35f500-a3b3-11eb-9ff9-5e3ade79666e.mov

**Comment by rkrishnasanka** [comment]
This is being fixed in v2
