### ISSUE TITLE
SVG File Download 

### ISSUE THREAD

**Issue by sebriquet** [CIDARLAB/3DuF#249]
**Describe the bug**
When trying to download the SVG files from 3Duf, the system downloads blank files  they show blank in chrome as well as with SVG viewer software.

**To Reproduce**
1. Go to 3Duf and complete your design
2. Click on SVG download
3. Open downloaded files (eg use Gapplin if using MAC)
4. See blank file

**Expected behavior**
The SVG file should be visible either in the URL or with a SVG viewer.

**Screenshots**
<img width="1149" alt="Screen Shot 2021-04-23 at 7 38 53 PM" src="https://user-images.githubusercontent.com/57968955/115939253-8e40cf00-a46b-11eb-8f6b-518b815f38b3.png">

**Desktop (please complete the following information):**
 - OS: iOS  (macOS Catalina)
 - Browser : Chrome 
 - Version: Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**

**Comment by rkrishnasanka** [comment]
@sebriquet could you try opening the SVG with inkscape (https://inkscape.org/) ? Upload the SVGs so that I can see if its just an issue with the browser not opening them properly

**Comment by sebriquet** [comment]
Hi Krishna,

Attached are the SVG files, I could not open them with inkspace either.

**Comment by rkrishnasanka** [comment]
@sebriquet You'll need to upload the svg on the github, I don't think it detects the attachments

**Comment by sebriquet** [comment]
GitHub is not letting me upload svg files: 
<img width="668" alt="Screen Shot 2021-04-27 at 10 01 11 AM" src="https://user-images.githubusercontent.com/57968955/116254629-802ad100-a73f-11eb-827d-44954586bd1f.png">

**Comment by rkrishnasanka** [comment]
Create a zip ?

**Comment by rkrishnasanka** [comment]
@sebriquet could you make a zip file of this design?

**Comment by rkrishnasanka** [comment]
Hey @sebriquet it seems like most of the svg issues are because you aren't opening the svg in Inkscape. I'm gonna close this issue since I don't have any way to check and see if the svg is working or not.
