### ISSUE TITLE
Cannot open json files created by 3duf previously from igem2017 MARS website

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#254]
![image](https://user-images.githubusercontent.com/38414177/116015788-278b0380-a66d-11eb-9d4f-152132c104b8.png)

**Comment by rkrishnasanka** [comment]
We won't be fixing 3DuF for this, the goal will be to host legacy, v1, v2 versions of 3DuF so that old designs can be opened.
