### ISSUE TITLE
Cannot add more than two valves correctly on one connection. It shows correctly when there is only one valve on it.

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#255]
![image](https://user-images.githubusercontent.com/38414177/116015839-52755780-a66d-11eb-9128-da344836ab50.png)
![image](https://user-images.githubusercontent.com/38414177/116015876-78026100-a66d-11eb-8f0f-5118084ff61c.png)

**Comment by jackruan99** [comment]
fixed
