### ISSUE TITLE
[Story] Covert Change All Components Dialog

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#259]
### Description

When the user clicks on the `CHANGE ALL` button on the double click menu, we need to pop up this menu. The menu contains UI that will let the user select all the components of the same type and decide whether or not to change the property values to reflect that of the current component.

Features:
1. Should provide a tabulated list of the different components, their names with an ability to select each of them
2. Should be able to `save` changes on clicking on the change button
3. Should be able to `cancel` the dialog 
4. Should have the ability to select/de-select all 

**Additional Description:** 

This is how the current dialog looks like:
![Screen Shot 2021-06-04 at 11 11 00 AM](https://user-images.githubusercontent.com/855696/120823576-90478480-c525-11eb-82dd-7dc775fb4345.png)

This is how the new version of this should look like:

<img width="892" alt="Screen Shot 2021-06-14 at 1 27 30 PM" src="https://user-images.githubusercontent.com/855696/121933615-4c6a3180-cd14-11eb-9762-2ac25f994d4e.png">

Acceptance Criteria:
- [ ] UI Unit Test Stub
- [ ] Add methods for the 
- [x] Change all method should have logic for changing the component properties using the Device/Component API
- [x] Should have all the logic for getting all the components of the given type and populating the table self-contained here

**Comment by vyiu** [comment]
I'm working on this
