### ISSUE TITLE
[Story] Convert the Grid Settings to Vue

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#261]
### Description

The gird settings button needs to be floating on the top left of the canvas, on clicking the button, a grid settings dialog should open up. This dialog will provide the user with the ability to:

1. Enable/Disable the automatic grid
2. Enable/Disable the rendering of Snap Points
3. Provide the user with a slider that will change the granularity of the grid

**Additional Description:** 

![Screen Shot 2021-06-04 at 11 57 00 AM](https://user-images.githubusercontent.com/855696/120830004-0ea72500-c52c-11eb-8b4e-4e440d308bea.png)

The button should have a tooltip on hovering 
![Screen Shot 2021-06-04 at 11 57 04 AM](https://user-images.githubusercontent.com/855696/120830040-18c92380-c52c-11eb-9928-df825f72b9a8.png)

On clicking the button the Grid menu should popup

![Screen Shot 2021-06-04 at 11 51 45 AM](https://user-images.githubusercontent.com/855696/120830101-267ea900-c52c-11eb-97c8-56bc31b20edf.png)

We used the NoUISlider in this demo. It seems like  Veeno is an alternative that we might be able to use: https://www.npmjs.com/package/nouislider-vue

Acceptance Criteria:
- [ ] Unit Test stubs for the component
- [ ] Should call the same API as given in the earlier version of Vue
- [ ] Should not have any linting error (must be fixed before the pull request)

**Comment by jkamoona** [comment]
#261
