### ISSUE TITLE
[Story] Create Component Library API

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#265]
### Description

In order to populate the different components available to the user. We need to create a single API that will have the following methods:

-[] `getAllComponents()` -> List[str]
-[] `getComponentWithMINT(str: mint_identifier)` -> LibraryObject

**Additional Description:**  This should be written in TypeScript

Ref - check `src/app/featureSets/featureSet.js` for reference

Acceptance Criteria:
- [ ] Unit Test method stubs
- [ ] Should not have any Linting errors

**Comment by msisk23** [comment]
I'll work on this
