### ISSUE TITLE
(JS-0003) Found constant expressions in conditions

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#267]
## Description
A constant expression such as a literal when used as a condition in an `if`/ `for` / `while` or `do...while` statement can cause errors in a production environment. &lt;!--more--&gt; Usage of such constructs in a development environment for debugging triggers is common, but it&#x27;s not a good practice to ship …

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/CIDARLAB/3DuF/issue/JS-0003/occurrences/](https://deepsource.io/gh/CIDARLAB/3DuF/issue/JS-0003/occurrences/)

**Comment by msisk23** [comment]
I'm working on this
