### ISSUE TITLE
(JS-0050) Avoid use of `==` and `!=`

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#270]
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`. If one of those occurs in an innocent-looking statement such as `a == b` the actual problem is very difficult to spot. &lt;!--more--&gt; The strict equality operators (`===` …

## Occurrences
There are 74 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/CIDARLAB/3DuF/issue/JS-0050/occurrences/](https://deepsource.io/gh/CIDARLAB/3DuF/issue/JS-0050/occurrences/)

**Comment by msisk23** [comment]
I'm working on this
