### ISSUE TITLE
[Story] Convert the Insert Text Dialog to Vue

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#273]
### Description

When the user clicks on the `INSERT TEXT` button a dialog pops up on the top-left corner of the canvas that provides the user with a text box and the options for how to place the text on the different layers.

1. Text Box where the user inputs the text
2. Text Input for the font height in mm
3. Drop down menus for the different layers in each level
4. Buttons that have the ability to cancel or insert the text
5. Ability to Preview the text and how big the font will be on the design

**Additional Description:** 

![Screen Shot 2021-06-08 at 9 21 16 PM](https://user-images.githubusercontent.com/855696/121277872-80220300-c89f-11eb-8106-e8487f2ae649.png)

Acceptance Criteria:
- [ ] The entire UI should match the layout shown in the mockup
- [ ] Add methods for all the button clicks
- [ ] Should have methods for opening and closing the dialog via EventBus
- [ ] Should not have any linting errors (must be fixed before the pull request

**Comment by lesliepu** [comment]
I'm working on this
