### ISSUE TITLE
move functionality out of pageSetup.js

### ISSUE THREAD

**Issue by Nesciosquid** [CIDARLAB/3DuF#44]
`pageSetup.js` currently contains way too much functionality that should be broken out into other classes. 

2D/3D transitions, the establishment and functionalization of buttons, and file processing functionality should probably be moved out into separate files. Ultimately, the buttons in the view should populate based on the FeatureSets which are currently being used, not hard-coded.

**Comment by rkrishnasanka** [comment]
This will be handled with another refactoring.
