### ISSUE TITLE
Issue adding flow and process components to new layer

### ISSUE THREAD

**Issue by Lujainkh** [CIDARLAB/3DuF#445]
Description:
I am unable to add flow components to the second layer of my design. Clicking on the button of the desired component does not select it and I cannot place it in my design.

To Reproduce:
1. Go to 'Select Layer'
2. Click on the small plus sign to add a new layer
3. click on 'Flow' on the second layer
4. Scroll down to 'Process'
5. Select 'Chamber'

Expected Behavior
tool will be selected and clicking on the device area will place it.

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.2.1
 - Browser: Chrome
 - Version: 100.0.4896.88 

Link of a video showing this problem is attached: https://drive.google.com/file/d/1seC0ifmAhw5jY1xvQ286pAkEgKJ02Mlw/view?usp=sharing

**Comment by rkrishnasanka** [comment]
This was fixed in commit dbe965adcc31b05f8521c6e2e3d366322772dd85 . We are going to depreciate some of this API in v2 to prevent these kinds of circular dependency calls that often cause the incorrect setup of object.s
