### ISSUE TITLE
Vertical and Horizontal Mixers of Same Parameters are Different

### ISSUE THREAD

**Issue by aonanam** [CIDARLAB/3DuF#54]
![image](https://cloud.githubusercontent.com/assets/6097214/18354352/3736dd80-75b3-11e6-9ffc-c56bcdde704d.png)

It seems like the vertical mixer doesn't take channel spacing into account. Neither of the previews of the mixers do, but upon placing the horizontal mixer, spacing is accounted for.

**Comment by JLippai** [comment]
Fixed in latest update on fluigi-visualizer branch
