### ISSUE TITLE
Incorrect Drawing of Fluigi Output

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#57]
![image](https://cloud.githubusercontent.com/assets/855696/20942304/d9e5a628-bbc8-11e6-9710-6294bd7cdf5d.png)

![image](https://cloud.githubusercontent.com/assets/855696/20942314/e88ff2d2-bbc8-11e6-86a0-d3e02cc398fa.png)

![image](https://cloud.githubusercontent.com/assets/855696/20942328/f2b4bc52-bbc8-11e6-8d81-6f1bfbb82496.png)

**Comment by JLippai** [comment]
This is a work in progress, but the fluigi-visualizer branch does not have these offset problems

**Comment by aonanam** [comment]
This bug is hilarious

**Comment by rkrishnasanka** [comment]
Not relevant anymore. Will be addressed in Parchmint Support
