### ISSUE TITLE
Microfluidic not Displaying - Error Reading Params

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#58]
Test JSON File: Simple Mixer
Available at - http://www.jsoneditoronline.org/?id=42de75901794aca94d17e04401f6a80e

Error Console Log:

![image](https://cloud.githubusercontent.com/assets/855696/20942618/25d86240-bbca-11e6-8066-7b28973fcc9d.png)

**Comment by JLippai** [comment]
This was fixed a while back; missed closing this
