### ISSUE TITLE
Show Volume for Component

### ISSUE THREAD

**Issue by jicargo** [CIDARLAB/3DuF#62]
It might be useful to show the volume of components like chambers as you change their size.  Alternatively, perhaps have a volume slider that automatically scales the component to the selected volume.

**Comment by JLippai** [comment]
Adding an indicator is an interesting idea, but I would shy away from making it the adjustable parameter on the slider. Scaling the volume on its own makes little sense when it inherently relies on at least two other paramters that are adjustable.
