### ISSUE TITLE
Improve trackpad movement compatibility

### ISSUE THREAD

**Issue by kandrilenas** [CIDARLAB/3DuF#64]
Adding the ability to pan the workspace with the trackpad (either with modifier keys + scrolling, or some other way) would be great!  I don't know how to move around the workspace without zooming in and out to move.

**Comment by rkrishnasanka** [comment]
Panning has been enabled in the commit - 82e57c645877f0aa7c2e5fe5ec4c8a4e3d532fa1

Thanks for the suggestions!
