### ISSUE TITLE
Output for mixer is incorrect

### ISSUE THREAD

**Issue by mzw23** [CIDARLAB/3DuF#66]
STL file does match design placed on grid no matter the configuration set for the mixer.

![image](https://cloud.githubusercontent.com/assets/4683301/24811788/856f5dbe-1b95-11e7-97e0-d0abd50394f9.png)

![image](https://cloud.githubusercontent.com/assets/4683301/24811780/7dd5ecb2-1b95-11e7-8ed6-5e4b92b7965b.png)

**Comment by JLippai** [comment]
Fix in progress; have temporarily disabled this functionality to remove confusion. Please use SVGs for now.
