### ISSUE TITLE
3DuF does not flip control layer for CNC milling

### ISSUE THREAD

**Issue by mzw23** [CIDARLAB/3DuF#67]
The SVG of the control layer must be flipped for correct milling. Currently 3DuF does not do this.

### Current 3DuF Control Output Example
<img width="511" alt="3duf svg control" src="https://cloud.githubusercontent.com/assets/4683301/25300457/e0e2d632-26dd-11e7-9bef-8c905883699c.png">

### Correct 3DuF Control Output Example
<img width="511" alt="correct svg control" src="https://cloud.githubusercontent.com/assets/4683301/25300458/e0e30b98-26dd-11e7-9ca7-83ab3a4d392d.png">

**Comment by rkrishnasanka** [comment]
I'd like to bring this up again as an issue. Earlier versions of 3DuF used to flip the chip horizontally. That needs to be reimplemented again.

**Comment by rkrishnasanka** [comment]
Implemented in the CNC outputs as of commit - 2545e9e5107388d6f9d0fec27bfa0b405c68d20f
