### ISSUE TITLE
JSON file issuse for 3DuF and other comments

### ISSUE THREAD

**Issue by mars20** [CIDARLAB/3DuF#68]
I noticed that the .json file downloaded from 3DuF does not save the design completely. The SVG files have the complete design but the .josn has an only partial design.

 

- [x] A right click menu with Cut, Copy and Paste option, Undo and redo option, move option
- [x] scroll bar for the canvas
- [ ] ~~Option to flip feature, currently, a rotation is supported~~
- [x] Option to use ESC key or some other key to deselect a selected feature.
- [x] Some feature names are different in 3DuF compared to MINT or NEPTUNE. The documentation of name convention between different tools will be useful.
- [ ] ~~Most features have square corners but option to use smooth corners will be useful as it has less probability of cells getting stuck in the corners.~~
- [x] Option to turn off grid in canvas

**Comment by JLippai** [comment]
This is a lot of items in one issue... with the exception of the first and last, these are feature requests. Can you specify what you mean by the JSON having a partial design? And which features have different names from those in MINT?
