### ISSUE TITLE
Fluigi tree not importing

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#70]
When you upload a JSON file from Fluigi the tree feature doesn't import properly.
![image](https://cloud.githubusercontent.com/assets/26445740/26514091/91b5ca9e-423d-11e7-9a12-2d0ebfd06801.png)
![image](https://cloud.githubusercontent.com/assets/26445740/26514095/a32ae7f0-423d-11e7-97fb-11d0a4eba3a5.png)

**Comment by JLippai** [comment]
This appears to primarily be an incompatibility between how 3DuF and Fluigi define the ends of the trees. Will review with @rkrishnasanka

**Comment by rkrishnasanka** [comment]
We have an updated version of ` TREE ` that needs to be changed in Fluigi/MINT.  Which works correctly over here.
