### ISSUE TITLE
SVG port & channel separation difficult

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#73]
When milling you need to have separate port and channel layers. Inkscape reads the SVG files from Neptune and allows group selection (click and drag a box, all within box selected) and deletion just fine, but 3Duf's SVG files require you to select each node individually (which can be very very tedious for difficult designs). 
Either ports & channels being exported on different export files, or the ability to select multiple channels at once (like it works with Neptune's SVG) in Inkscape would be v helpful.

**Comment by JLippai** [comment]
Separate output of port "layer" SVG is in the works

**Comment by rkrishnasanka** [comment]
Refer to #100 for this issue's solution. The idea is that we will start separating SVG's by the operation.
