### ISSUE TITLE
Chamber 

### ISSUE THREAD

**Issue by dinithi-s** [CIDARLAB/3DuF#77]
Using the chamber primitive on 3Duf is confusing, making it similar to the diamond chamber (click and drop with the ability to specify length and width) would be much easier to manage.

**Comment by JLippai** [comment]
Agreed. I will likely have both versions in 3DuF, though, since there is merit to the click-and-drag approach as well.

**Comment by rkrishnasanka** [comment]
I would argue against click and drag, since you can't measure dimensions or change anything later on
