### ISSUE TITLE
Y Tree Mixer

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#80]
A Y tree mixer would be very useful as they are more effective than T tree mixers.

**Comment by JLippai** [comment]
Good idea! Will implement in tandem with Krishna in MINT.

**Comment by rkrishnasanka** [comment]
Added the component ` Y-Tree ` 

Ref Commit - bf9a5a7ced316d69ab00a6e4619b96b7fd1b254f
