### ISSUE TITLE
Border doesn't scale to chip size

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#81]
When you edit the size of your chip using JSON, the border 3Duf creates doesn't automatically scale properly.
![image](https://user-images.githubusercontent.com/26445740/27054476-023490da-4f8f-11e7-85bb-8c63ecd48051.png)
(Chip size: 97mm x 63mm)

**Comment by rkrishnasanka** [comment]
This has been fixed as of commit ee4c134e7afd9c609cb204305251ff56f9fca822 it also allows the user to setup different kinds of device borders with DXF files
