### ISSUE TITLE
360 Degree rotation of components

### ISSUE THREAD

**Issue by dinithi-s** [CIDARLAB/3DuF#83]
The ability to set  primitive on the grid and then rotate it would be extremely helpful - especially when creating a fan branch or circular designs.

**Comment by rkrishnasanka** [comment]
We have the 360-degree rotation now for Gradient Generator. We need to figure out how we can incorporate this into all the other components. We also need to figure out a strategy for accommodating the older files. Perhaps a script would be sufficient for converting all the other JSON features.

**Comment by rkrishnasanka** [comment]
So we are slowly transitioning all the components to have 360-degree rotations and including code to modify the design files automatically without the need of an external script.
