### ISSUE TITLE
Mixer does not mill properly 

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#86]
When trying to mill out this design:
![flow_channels](https://user-images.githubusercontent.com/26445740/27487262-39efe4a0-5801-11e7-98e1-cbb53355d919.png)
The mixers did not mill out correctly:
![win_20170623_10_45_46_pro](https://user-images.githubusercontent.com/26445740/27487274-435fb36c-5801-11e7-9df1-0eeaf1ff5e40.jpg)
When milling, the mill reads each part of the mixer as a separate channel, not as one entire feature, so it does not cut it out correctly. Using an exacto knife to cut the excess polycarb blocking the channels leads to the chip becoming mangled (as you can see in the picture) and not uniform.
Multiple people have encountered this issue with endmills of varying sizes. 
Ideally, the mill would follow the path of the mixer when milling instead of cutting individual channels and then (failing to properly) connect them. I'm not sure how to make that happen, but if it could that would be great.

**Comment by sivwizinbiznilva** [comment]
This can be mitigated by performing an SVG union, as it seems 3DuF export each vector as an individual entity.

**Comment by sarahnem** [comment]
How do you perform an SVG union?

**Comment by sivwizinbiznilva** [comment]
https://imagesbyheatherm.wordpress.com/2010/01/15/inkscape-path-operations-explained-part-1/

Union or stroke-to-path should do the trick! Inkscape is free.

**Comment by JLippai** [comment]
There is an experimental fix for this that currently hurts some of the live-update functionality of the sliders. Will test it more and iron out kinks.

**Comment by JLippai** [comment]
The new live "Better Mixer" primitive resolves this issue, and will replace the old Mixer as the only square Mixer primitive in the next couple of days
