### ISSUE TITLE
Ability to Flip Mixers

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#89]
![image](https://user-images.githubusercontent.com/26445740/27914012-e2e02ede-622f-11e7-9eaa-97c17fc19eac.png)
It would be nice if we had the option to flip/reflect mixers. In situations that use trees + mixers, this would allow for more accurate symmetry.

**Comment by rkrishnasanka** [comment]
Fluigi actually adds small lines that extends the bends so that this feature isn't necessary.

**Comment by rkrishnasanka** [comment]
New mixers have standard sizes, this should not be an issue anymore
