### ISSUE TITLE
Square vs Circle Channel Tool

### ISSUE THREAD

**Issue by sarahnem** [CIDARLAB/3DuF#95]
![image](https://user-images.githubusercontent.com/26445740/29461853-3f27593c-83fb-11e7-87c5-7911b686b592.png)
Now that channels end in rectangles, the circle channel drawing tool is a bit confusing & doesn't line up quite properly. If it could be a square instead for hard channels that would be gucci.

**Comment by JLippai** [comment]
Will implement this in the next couple of days

**Comment by JLippai** [comment]
This has been implemented
